apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
secretGenerator:
  - literals:
      - api_key=$SOLAREDGE_KEY
    name: solaredge
    type: Opaque
images:
  - name: ghcr.io/clambin/solaredge-exporter
    newTag: $TAG
