{
 "title": "solar panels",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Power mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (site) (solaredge_inverter_power_limit)",
     "legendFormat": "voltage"
    }
   ]
  },
  {
   "title": "Output",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (siteid) (solaredge_current_power)"
    }
   ]
  },
  {
   "title": "Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (siteid) (solaredge_day_energy)"
    }
   ]
  },
  {
   "title": "Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (siteid) (solaredge_month_energy)"
    }
   ]
  },
  {
   "title": "Year",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (siteid) (solaredge_year_energy)"
    }
   ]
  },
  {
   "title": "Output (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by (siteid) (solaredge_current_power)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (site) (solaredge_inverter_temperature)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output (V, A)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg by (site) (solaredge_inverter_ac_voltage)",
     "legendFormat": "AC voltage"
    },
    {
     "expr": "avg by (site) (solaredge_inverter_dc_voltage)",
     "legendFormat": "DC voltage"
    },
    {
     "expr": "avg by (site) (solaredge_inverter_ac_current)",
     "legendFormat": "AC current"
    }
   ]
  }
 ]
}