---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solaredge-exporter
  labels:
    app: solaredge-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solaredge-exporter
  template:
    metadata:
      labels:
        app: solaredge-exporter
    spec:
      restartPolicy: Always
      containers:
      - name: solaredge-exporter
        image: ghcr.io/clambin/solaredge-exporter
        args:
        #- '--debug'
        - '--apikey=$(api_key)'
        env:
        - name: TZ
          value: "Europe/Brussels"
        envFrom:
        - secretRef:
            name: solaredge
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          #limits:
          #  memory: 32Mi
---
